version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  ${APP_PORT:-5000}:5000
    volumes:
      - './app:/app'
    networks:
      - mynet
    environment:
      DB_URL: ${DB_URL:-mysql://root:root@mysql/my_db}
      DEBUG: ${DEBUG:-true}
    depends_on:
      - mysql

  mysql:
    image: mysql
    networks:
      - mynet
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-my_db}
    volumes:
      - mysql_data:/var/lib/mysql
  
networks:
  mynet:

volumes:
  mysql_data: